# Site settings
title: Essays on System Programming
email: yshen@hybridkernel.com
description: > # this means to ignore newlines until "baseurl:"
    The author is too lazy to write anything.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kernelin.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: yyshen 

# Build settings
markdown: kramdown
theme: minima
