# Site settings
title: ys 
email: kernelin@gmx.com 
description: > # this means to ignore newlines until "baseurl:"
  A personal blog about programming
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://kernelin.com" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username: yyshen 

# Build settings
markdown: kramdown
